# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: echo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x04\x65\x63ho\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x9d\x01\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x43\n\x11received_metadata\x18\x02 \x03(\x0b\x32(.echo.EchoResponse.ReceivedMetadataEntry\x1a\x37\n\x15ReceivedMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32<\n\x0b\x45\x63hoService\x12-\n\x04\x45\x63ho\x12\x11.echo.EchoRequest\x1a\x12.echo.EchoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHORESPONSE_RECEIVEDMETADATAENTRY']._loaded_options = None
  _globals['_ECHORESPONSE_RECEIVEDMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_ECHOREQUEST']._serialized_start=20
  _globals['_ECHOREQUEST']._serialized_end=50
  _globals['_ECHORESPONSE']._serialized_start=53
  _globals['_ECHORESPONSE']._serialized_end=210
  _globals['_ECHORESPONSE_RECEIVEDMETADATAENTRY']._serialized_start=155
  _globals['_ECHORESPONSE_RECEIVEDMETADATAENTRY']._serialized_end=210
  _globals['_ECHOSERVICE']._serialized_start=212
  _globals['_ECHOSERVICE']._serialized_end=272
# @@protoc_insertion_point(module_scope)
